sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t docker-react-image .
script:
  - docker run -e CI=true docker-react-image npm run test # npm run test does not exit immediately.
# A new flag -e CI=true is required for this command to work.
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "DockerApp"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-us-west-1-615533125910"
  bucket_path: "DockerApp"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
