sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t docker-react-image .
script:
  - docker run -e CI=true docker-react-image npm run test # npm run test does not exit immediately.
# A new flag -e CI=true is required for this command to work.